name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display Softuni username
      run: echo "steffy96"

  ui-test:
    runs-on: ubuntu-latest
    needs: build-unit-test

    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Run UI tests
      run: npm run test:ui